import { Header } from 'components/Header'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Storybook Addon Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <p>
          If in storybook, click on any one of the stories on the left to see
          supported features
        </p>
        <p>
          If running the nextjs dev server, click on any one of the above links
          to see supported features
        </p>
      </main>
    </div>
  )
}
